name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser l'image Ubuntu la plus récente

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2  # Action pour récupérer le code source du dépôt

      - name: Installer Docker
        run: sudo apt-get install docker.io -y  # Installer Docker sur l'image Ubuntu

      - name: Construire l'image Docker nginx
        run: docker build -t 3dvp_project .  # Construire l'image Docker à partir du Dockerfile

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utiliser les secrets GitHub pour sécuriser le nom d'utilisateur Docker
          password: ${{ secrets.DOCKER_PASSWORD }}  # Utiliser les secrets GitHub pour sécuriser le mot de passe Docker

      - name: Pousser l'image Docker vers Docker Hub
        run: |
          docker tag 3dvp_project ${{ secrets.DOCKER_USERNAME }}/3dvp_project:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/3dvp_project:latest

     
